;;; Export every org page under docs/orgmode to reStructuredText under docs/source.
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(unless (package-installed-p 'ox-rst)
  (package-refresh-contents)
  (package-install 'ox-rst))
(require 'ox-rst)
(let* ((docs (file-name-directory (or load-file-name buffer-file-name)))
       (source (expand-file-name "orgmode" docs))
       (output (expand-file-name "source" docs)))
  (dolist (file (directory-files-recursively source "\\.org$"))
    (let ((relative (file-relative-name file source)))
      (with-current-buffer (find-file-noselect file)
        (let ((destination (expand-file-name (concat (file-name-sans-extension relative) ".rst") output)))
          (make-directory (file-name-directory destination) t)
          (org-export-to-file 'rst destination))))))
