name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test --features capi --verbose
      - name: Clippy
        run: cargo clippy --features capi -- -D warnings
      - name: Format
        run: cargo fmt --check
